### ISSUE TITLE
HA config

### ISSUE THREAD

**Issue by haivala** [carohauta/oma-helen-ha-integration#13]
Käytän HA:ssa sitä default dashboardia, jonka siis HA configuroi eli en käytä myöskään lovelace kortteja.
Aikaisemmin data oli kivasti samassa lattikossa jonka nimi on Helen.

Nyt kun tämä näyttää myös kuukausikulutuksen ja siirto kulut niin nämä tiedot löytyvät Sensors laattikosta HA:ssa. Miten saisin kaiken tämän integraation datan samaan laatikkoon?

Ajattelin kysyä, kun taitaa olla helpompi että integraatioon muuttaa jotain?

**Comment by carohauta** [comment]
Mulla näyttäis kaikki menneen sinne Sensors-laatikon sisään. Tarvii hieman ihmetellä, että millä perusteella nää määräytyy. 

Sellaista voisit kokeilla, että jos laitat ne kaikki entityt yhden groupin sisään `/config/groups.yaml` -tiedostoon.

Esimerkki omasta `/config/groups.yaml` fileestä, jolla olen groupannut pihavalot yhden laatikon sisään:
```yaml
outdoor_lights:
  name: Outdoor lights
  entities:
    - switch.on_off_plug_in_unit_1
    - switch.on_off_plug_in_unit_2
    - light.color_temperature_light_1
    - light.color_temperature_light_2
    - light.color_temperature_light_3
```
