### ISSUE TITLE
Kaksi asuntoa ja kaksi erinlaista sopimista

### ISSUE THREAD

**Issue by Eerotuomenoksa** [carohauta/oma-helen-ha-integration#26]
Hei, kiitos upeasta työstäsi. Tämä toimii loistavasti!
Minulla on kesämökki, jossa on pörssisähkösopimus, kotona taas kiinteä hinta. Mietin olisiko mahdollista saada kumpikin näkyviin omille erilliselle dashboard-korteille?

**Comment by carohauta** [comment]
Voit lisätä konffiin useita sensoreita eri käyttöpaikkatunnuksella, jolloin saat entityt molemmille soppareille. 

Esimerkiksi pörssisähkö näin:
```yaml
  - platform: helen_energy
    username: !secret oma_helen_username
    password: !secret oma_helen_password
    vat: 0.255
    delivery_site_id: 643001234567891234 # käyttöpaikkatunnus
    contract_type: EXCHANGE # tämä on kiinteässä sopparissa FIXED ja pörssissä EXCHANGE
  - platform: template
    sensors:
      helen_exchange_energy_consumption:
        friendly_name: "This month energy consumption"
        unit_of_measurement: "kWh"
        icon_template: mdi:lightning-bolt
        device_class: "energy"
        value_template: >
          {{ 0 if state_attr('sensor.helen_exchange_electricity', 'current_month_consumption') == None else state_attr('sensor.helen_exchange_electricity', 'current_month_consumption') | round() }}
      helen_exchange_energy_consumption_last_month:
        friendly_name: "Last month energy consumption"
        unit_of_measurement: "kWh"
        icon_template: mdi:lightning-bolt
        value_template: >
          {{ 0 if state_attr('sensor.helen_exchange_electricity', 'last_month_consumption') == None else state_attr('sensor.helen_exchange_electricity', 'last_month_consumption')| round() }}
      helen_exchange_energy_last_month_total_cost:
        friendly_name: "Last month energy cost"
        unit_of_measurement: "e"
        icon_template: mdi:currency-eur
        value_template: >
            {{ 0 if state_attr('sensor.helen_exchange_electricity', 'last_month_total_cost') == None else state_attr('sensor.helen_exchange_electricity', 'last_month_total_cost') | round() }}
      helen_exchange_energy_daily_average_consumption:
        friendly_name: "Daily average consumption"
        unit_of_measurement: "kWh"
        icon_template: mdi:lightning-bolt
        value_template: >
          {{ 0 if state_attr('sensor.helen_exchange_electricity', 'daily_average_consumption') == None else state_attr('sensor.helen_exchange_electricity', 'daily_average_consumption') | round() }}
```

Samanlainen rimpsu vastaavasti toiselle sopparille (eri delivery_site_id ja contract_type). Mikäli käytät template-entityjä, tulee niilläkin olla uniikit nimet.
