### ISSUE TITLE
Small details to integrate to HASS energy board

### ISSUE THREAD

**Issue by atol71** [carohauta/oma-helen-ha-integration#9]
Hi,
One can find info needed to integrate sensors to energy dashboard:
`https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics`
It is just some additional plugin values passed so that the statistics engine detects sensor type.

Hope it helps! When I have time I can type those in too into code....

**Comment by atol71** [comment]
Hi,
One needs to add:
```
      helen_smart_guarantee_energy_consumption:
        friendly_name: "This month energy consumption"
        unit_of_measurement: kWh
        device_class: energy
...
```
into helen_smart_guarantee_energy_consumption and include customization config include:
```
...
homeassistant:
  customize: !include customize.yaml
...
```
and in customize.yaml:
```
sensor.helen_smart_guarantee_energy_consumption:
  state_class: total
  last_reset: None
```
And it works with HASS energy board!
Atol
